using UnityEngine;

namespace Lamplighter
{
    /// <summary>
    /// The lamplighter. The body is a DreamLayer sprite character: its clips and Animator were
    /// generated by the DreamLayer sprite importer, with the pivot on the feet.
    /// </summary>
    public class Player : MonoBehaviour
    {
        /// <summary>On-screen height of the lamplighter, in units (118 design pixels).</summary>
        public const float HeroHeight = 1.18f;

        public float Flame = Config.FlameStart;
        public readonly LightSource Light = new LightSource(Vector2.zero, 0f, 1f);
        /// <summary>Set while a flare burst is expanding; the game burns wisps inside it.</summary>
        public float FlareRadius;
        public bool Frozen;
        /// <summary>-1, 0 or 1: the direction the player is pushing, used for camera look-ahead.</summary>
        public int MoveDir;

        public bool IsInvulnerable => Time.time < _invulnUntil;
        public Vector2 Pos => transform.position;

        private Rigidbody2D _rb;
        private Transform _body;
        private SpriteRenderer _sprite;
        private Animator _anim;
        private SpriteRenderer _glow;
        private Emitter _dust;
        private CameraRig _rig;
        private Tween.Handle _squash;

        private float _coyoteUntil, _jumpBufferedUntil, _invulnUntil, _knockUntil, _flareReadyAt, _stepTimer, _flicker;
        private bool _jumpHeld, _wasGrounded, _grounded;
        private string _animState;
        private int _touchDir;
        private bool _touchJump, _touchJumpPrev, _botJumpPrev;

        public static Player Create(Transform world, Vector2 pos, CameraRig rig)
        {
            var go = new GameObject("Player");
            go.transform.SetParent(world, false);
            go.transform.position = pos;
            var p = go.AddComponent<Player>();
            p._rig = rig;
            p.Build();
            return p;
        }

        private void Build()
        {
            _rb = gameObject.AddComponent<Rigidbody2D>();
            _rb.freezeRotation = true;
            _rb.interpolation = RigidbodyInterpolation2D.Interpolate;
            _rb.collisionDetectionMode = CollisionDetectionMode2D.Continuous;
            _rb.gravityScale = 1f;

            // A narrow body at the feet feels fair on ledges; the lantern and cloak overhang it.
            var box = gameObject.AddComponent<BoxCollider2D>();
            box.size = new Vector2(0.28f, 1.0f);
            box.edgeRadius = 0.02f;
            box.offset = new Vector2(0f, 0.52f);
            box.sharedMaterial = new PhysicsMaterial2D("NoFriction") { friction = 0f, bounciness = 0f };

            var body = new GameObject("Body");
            body.transform.SetParent(transform, false);
            _body = body.transform;
            _sprite = body.AddComponent<SpriteRenderer>();
            _sprite.sortingOrder = Config.Order.Player;
            _anim = body.AddComponent<Animator>();
            _anim.runtimeAnimatorController = Res.HeroController;

            _glow = Res.MakeGlow(transform.parent, Config.Hex(0xffb35c), 0.5f);
            _dust = Emitter.Create("dust", FxPresets.Dust(), transform.parent, transform.position);
            Play("hero_idle");
        }

        public void SetTouch(int dir, bool jump)
        {
            _touchDir = dir;
            _touchJump = jump;
        }

        /// <summary>Returns true if the hit landed (not invulnerable or frozen).</summary>
        public bool Hurt(float fromX)
        {
            if (IsInvulnerable || Frozen) return false;
            _invulnUntil = Time.time + Config.InvulnTime;
            _knockUntil = Time.time + 0.22f;
            Flame = Mathf.Max(0f, Flame - Config.WispHitFlame);
            float side = Mathf.Sign(transform.position.x - fromX);
            if (side == 0f) side = 1f;
            _rb.velocity = new Vector2(side * 3.2f, 3.8f);
            GameAudio.I.Hurt();
            _rig.Shake(0.18f, 0.006f);
            return true;
        }

        public bool TryFlare()
        {
            if (Time.time < _flareReadyAt || Flame < Config.FlareCost + 0.02f)
            {
                if (Time.time >= _flareReadyAt) GameAudio.I.Denied();
                return false;
            }
            _flareReadyAt = Time.time + Config.FlareCooldown;
            Flame -= Config.FlareCost;
            GameAudio.I.Flare();
            FlareRadius = 0.01f;
            Tween.Value(0.4f, Config.FlareRadius, 0.38f, v => FlareRadius = v, Ease.CubicOut, onComplete: () => FlareRadius = 0f, owner: this);
            return true;
        }

        public void Respawn(Vector2 pos)
        {
            _rb.position = pos;
            transform.position = pos;
            _rb.velocity = Vector2.zero;
            Flame = Mathf.Max(Flame, Config.FlameRespawn);
            _invulnUntil = Time.time + 1.5f;
            Frozen = false;
        }

        public void Stop(bool horizontalOnly = false)
        {
            _rb.velocity = horizontalOnly ? new Vector2(0f, _rb.velocity.y) : Vector2.zero;
        }

        private bool CheckGrounded()
        {
            if (_rb.velocity.y > 0.05f) return false;
            var feet = (Vector2)transform.position + new Vector2(0f, -0.01f);
            return Physics2D.OverlapBox(feet, new Vector2(0.26f, 0.06f), 0f, 1 << Config.SolidLayer) != null;
        }

        private void Update()
        {
            if (Time.timeScale <= 0f) return;
            float dt = Time.deltaTime;
            float now = Time.time;
            _grounded = CheckGrounded();

            // ---- input
            int dir = 0;
            bool jumpDown = false, jumpPressed = false;
            if (!Frozen && Autopilot.Active)
            {
                dir = Autopilot.Dir;
                jumpDown = Autopilot.Jump;
                jumpPressed = Autopilot.Jump && !_botJumpPrev;
            }
            else if (!Frozen)
            {
                if (Input.GetKey(KeyCode.LeftArrow) || Input.GetKey(KeyCode.A)) dir -= 1;
                if (Input.GetKey(KeyCode.RightArrow) || Input.GetKey(KeyCode.D)) dir += 1;
                if (dir == 0) dir = _touchDir;
                jumpDown = Input.GetKey(KeyCode.Space) || Input.GetKey(KeyCode.UpArrow) || Input.GetKey(KeyCode.W) || _touchJump;
                jumpPressed = Input.GetKeyDown(KeyCode.Space) || Input.GetKeyDown(KeyCode.UpArrow) || Input.GetKeyDown(KeyCode.W) ||
                              (_touchJump && !_touchJumpPrev);
                if (Input.GetKeyDown(KeyCode.X) || Input.GetKeyDown(KeyCode.K) || Input.GetKeyDown(KeyCode.LeftShift) ||
                    Input.GetKeyDown(KeyCode.RightShift)) TryFlare();
            }
            _touchJumpPrev = _touchJump;
            _botJumpPrev = Autopilot.Jump;

            // ---- horizontal movement with acceleration, so the lamplighter has a little weight
            var v = _rb.velocity;
            float target = dir * Config.RunSpeed;
            float accel = _grounded ? (dir == 0 ? Config.Friction : Config.RunAccel) : Config.AirAccel;
            float dv = target - v.x;
            if (now >= _knockUntil) v.x += Mathf.Sign(dv) * Mathf.Min(Mathf.Abs(dv), accel * dt);
            if (dir != 0) _sprite.flipX = dir < 0;
            MoveDir = dir;

            // ---- jumping: coyote time + buffered input + variable height
            if (_grounded) _coyoteUntil = now + Config.CoyoteTime;
            if (jumpPressed) _jumpBufferedUntil = now + Config.JumpBufferTime;
            if (_jumpBufferedUntil > now && _coyoteUntil > now)
            {
                v.y = Config.JumpVelocity;
                _jumpBufferedUntil = 0f;
                _coyoteUntil = 0f;
                _grounded = false;
                GameAudio.I.Jump();
                Squash(0.82f, 1.18f);
                _dust.ExplodeAt(6, (Vector2)transform.position + new Vector2(0f, 0.04f));
            }
            if (!jumpDown && _jumpHeld && v.y > 0f) v.y *= Config.JumpCutMultiplier;
            _jumpHeld = jumpDown;
            v.y = Mathf.Max(v.y, -Config.MaxFallSpeed);
            _rb.velocity = v;

            if (_grounded && !_wasGrounded)
            {
                GameAudio.I.Land();
                Squash(1.2f, 0.8f);
                _dust.ExplodeAt(9, (Vector2)transform.position + new Vector2(0f, 0.04f));
            }
            _wasGrounded = _grounded;

            // ---- animation
            if (!_grounded) Play("hero_jump");
            else if (Mathf.Abs(v.x) > 0.3f)
            {
                Play("hero_run");
                _stepTimer -= dt;
                if (_stepTimer <= 0f)
                {
                    GameAudio.I.Step();
                    _stepTimer = 0.26f;
                }
            }
            else Play("hero_idle");

            // ---- invulnerability blink
            var c = _sprite.color;
            c.a = IsInvulnerable ? (Mathf.FloorToInt(now / 0.08f) % 2 == 1 ? 0.45f : 1f) : 1f;
            _sprite.color = c;

            // ---- the lantern: its light shrinks as the flame burns down, and flickers
            _flicker += dt * 9f;
            float f = Mathf.Clamp01(Flame);
            float flick = 1f + Mathf.Sin(_flicker) * 0.03f + Mathf.Sin(_flicker * 2.7f) * 0.02f;
            var pos = (Vector2)transform.position;
            var lantern = pos + new Vector2((_sprite.flipX ? -1f : 1f) * 0.3f, HeroHeight * 0.55f);
            Light.Pos = lantern;
            Light.Radius = (Config.LanternRadiusMin + (Config.LanternRadiusMax - Config.LanternRadiusMin) * f) * flick + FlareRadius;
            Light.Intensity = f <= 0f ? 0f : 0.55f + f * 0.45f;

            _glow.transform.position = lantern;
            _glow.transform.localScale = Vector3.one * (Light.Radius / 1.28f * 0.55f);
            var gc = _glow.color;
            gc.a = 0.18f + f * 0.3f + (FlareRadius > 0f ? 0.35f : 0f);
            _glow.color = gc;
        }

        private void Play(string state)
        {
            if (_animState == state) return;
            _animState = state;
            _anim.Play(state, 0, 0f);
        }

        /// <summary>Squash and stretch: the feet stay planted because the body's pivot is at the feet.</summary>
        private void Squash(float sx, float sy)
        {
            _squash?.Kill();
            _body.localScale = new Vector3(sx, sy, 1f);
            _squash = Tween.Run(0.18f, t =>
            {
                if (_body) _body.localScale = new Vector3(Mathf.LerpUnclamped(sx, 1f, t), Mathf.LerpUnclamped(sy, 1f, t), 1f);
            }, Ease.BackOut, owner: this);
        }

        private void OnDestroy()
        {
            if (_glow) Destroy(_glow.gameObject);
            if (_dust) Destroy(_dust.gameObject);
        }
    }
}
